version: "2"

services:
    # Core configuration
    php-fpm:
        container_name: toDoAndCo_php-fpm
        build:
            context: .
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: 'a7c67634-5e4b-4afb-812f-e6d12984da04'
            BLACKFIRE_SERVER_TOKEN: '80b4a84db81eeec45e752f5559f5e9c37a7b83df6399c3042fac19704e8a78df'
        ports:
            - 9600:9000
        volumes:
            - './:/var/www/toDoAndCo:rw,delegated'
            - './docker/php/conf/php.ini:/usr/local/etc/php/php.ini'
            - './docker/php/conf/production/php.ini:/usr/local/etc/php/php.ini'
        restart: always

    nginx:
        container_name: toDoAndCo_nginx
        image: nginx
        ports:
            - 8086:80
        links:
            - php-fpm
        volumes:
            - './:/var/www/toDoAndCo:rw'
            - './docker/nginx/conf/core/nginx.conf:/etc/nginx/nginx.conf'
            - './docker/nginx/conf/development/toDoAndCo.conf:/etc/nginx/conf.d/default.conf'
#            - './docker/nginx/conf/production/toDoAndCo.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/logs/:/var/log/nginx'
        restart: always

    # VARNISH
    varnish:
        container_name: toDoAndCo_varnish
        image: emgag/varnish:6.0
        volumes:
            - './docker/varnish:/etc/varnish:rw'
        ports:
            - "8082:80"

    # Server optimization
    redis:
        container_name: toDoAndCo_redis
        image: redis:alpine
        ports:
            - '6380:6379'
        links:
            - php-fpm
        restart: always

    mysql:
        image: mysql:5.7
        volumes:
            - "data-db:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: toDoAndCo
            MYSQL_USER: lolo
            MYSQL_PASSWORD: test
        ports:
            - "3307:3306"
            - "33060:33060"

    # Performances configuration
    blackfire:
        container_name: toDoAndCo_blackfire
        image: blackfire/blackfire
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: 'a7c67634-5e4b-4afb-812f-e6d12984da04'
            BLACKFIRE_SERVER_TOKEN: '80b4a84db81eeec45e752f5559f5e9c37a7b83df6399c3042fac19704e8a78df'
            BLACKFIRE_CLIENT_ID: '8d309eeb-5bf6-431a-8f68-4b57ffac80ec'
            BLACKFIRE_CLIENT_TOKEN: '8f925ffa61c6481d3ff8b3e35bd43e6c3f499ab5d0edf8a2996d7d9c47f8dce2'
        links:
            - php-fpm
        volumes:
            - './:/var/www/toDoAndCo:rw,cached'
        restart: always
volumes:
    data-db: {}
