AppBundle\Models\Entity\User:
    properties:
        username:
            - NotBlank:
#                message: 'Vous devez saisir un nom d'utilisateur
            - Length:
                min: 6
                minMessage : 'Le pseudo doit contenir au moins 6 caractères'
                groups: ["user"]

        password:
            - NotBlank:
#                message: Vous devez saisir un mot de passe'
            - Length:
                min: 8
                max: 50
                minMessage : 'Le mot de passe doit contenir au moins 8 caractères'
                groups: ["user"]

        email:
            - NotBlank:
#                message: 'Vous devez saisir une adresse email'
            - Email:
                mode: loose
                message: 'Le format de l'adresse n'est pas correcte.'
                groups: ["user"]
